import type { Metadata } from "next";
import "./globals.css";
import QueryClientProvider from "./QueryClientProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProvider>
      <html lang="pt-br">
        <body className="bg-dark">{children}</body>
      </html>
    </QueryClientProvider>
  );
}
